[web]
enabled = true
url = "proxy.meng.zip:8080"

database = "./remazarin.db"

[admin]
enabled = true
url = "admin.meng.zip:8081"

[[routes]]
url = "test.meng.zip:6789"
target = "localhost:9000"
tls = true
cert = "./certs/domain.cert"
key = "./certs/private.key"

[[routes]]
url = "test4.meng.zip:6789"
target = "localhost:9000"
tls = true
cert = "./certs/domain.cert"
key = "./certs/private.key"

[[routes]]
url = "test2.meng.zip/public:8080"
target = "192.168.129.130:9001"